version: '3.8'

services:
  app:
    container_name: telegram-stickeroptimizer-app
    image: chialab/php-dev:8.2-apache
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./.docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - telegram-stickeroptimizer-network

  db:
    container_name: telegram-stickeroptimizer-db
    image: mariadb
    volumes:
      - db-volume:/var/lib/mysql
      - ./.docker/my.cnf:/etc/mysql/mariadb.conf.d/my.cnf
      - ./.docker/dumps:/home/dumps
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: botdb
      MYSQL_USER: botdb
      MYSQL_PASSWORD: botdb
    ports:
      - "3306:3306"
    networks:
      - telegram-stickeroptimizer-network

  db-test:
    container_name: telegram-stickeroptimizer-db-test
    image: mariadb
    volumes:
      - db-test-volume:/var/lib/mysql
      - ./.docker/my.cnf:/etc/mysql/mariadb.conf.d/my.cnf
      - ./.docker/dumps:/home/dumps
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: botdb-test
      MYSQL_USER: botdb-test
      MYSQL_PASSWORD: botdb-test
    ports:
      - "3307:3306"
    networks:
      - telegram-stickeroptimizer-network

volumes:
  db-volume:
    name: telegram-stickeroptimizer-db-volume
  db-test-volume:
    name: telegram-stickeroptimizer-db-test-volume

networks:
  telegram-stickeroptimizer-network:
    driver: bridge
