name: Deploy
on:
  push:
    branches:
      - master
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: composer run tests

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 'Production'
    needs:
      - tests
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ${{ secrets.PROJECT_PATH}}
            php8.1 artisan down
            git reset --hard
            git pull "https://Lukasss93:${{ secrets.GIT_TOKEN }}@github.com/Lukasss93/telegram-stickeroptimizer.git" master
            php8.1 composer.phar install --no-dev --optimize-autoloader --no-ansi --no-interaction --no-progress
            php8.1 artisan migrate --force --step
            php8.1 artisan optimize
            php8.1 artisan storage:link
            php8.1 artisan nutgram:register-commands
            php8.1 artisan up
            echo 'DONE!'
