name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ${{ secrets.PROJECT_PATH}}
            php artisan down
            git reset --hard
            git pull "https://Lukasss93:${{ secrets.GIT_TOKEN }}@github.com/Lukasss93/telegram-stickeroptimizer.git" master
            php composer.phar install --no-dev --optimize-autoloader --no-ansi --no-interaction --no-progress
            php artisan migrate --force --step
            php artisan optimize
            php artisan storage:link
            php artisan nutgram:register-commands
            php artisan up
            echo 'DONE!'
